services:
  server:
    build:
      context: ./server
      target: frankenphp_dev
    volumes:
      - ./server:/app
      - ./server/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./server/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    # If you develop on Mac or Windows you can remove the vendor/ directory
    #  from the bind-mount for better performance by enabling the next line:
    #- /app/vendor
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
      CLIENT_URL: https://blitz-task.docker.localhost
      SENDER_EMAIL: noreply@blitz-task.docker.localhost
      MAILER_DSN: smtp://mailer:1025
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    labels:
      - "traefik.http.routers.blitz-task-server-http.rule=Host(`server.blitz-task.docker.localhost`)"
  # - "traefik.http.routers.blitz-task-server.rule=Host(`server.blitz-task.docker.localhost`)"

  client:
    build: 
      target: node_dev
    labels:
      - "traefik.http.routers.blitz-task-client-http.rule=Host(`blitz-task.docker.localhost`)"
      - "traefik.http.routers.blitz-task-client.rule=Host(`blitz-task.docker.localhost`)"
    volumes:
      - ./client:/app
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://server.blitz-task.docker.localhost
    extra_hosts:
      - host.docker.internal:host-gateway
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - ./client/node_modules/
        - action: rebuild
          path: ./client/package.json

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
    networks:
      - web-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blitz-task-database.entrypoints=web"
      - "traefik.http.routers.blitz-task-database.rule=Host(`db.blitz-task.docker.localhost`)"
      - "traefik.http.services.blitz-task-database.loadbalancer.server.port=5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  # mailer:
  #   image: axllent/mailpit
  #   ports:
  #     - "1025"
  #     - "8025"
  #   environment:
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
  #   networks:
  #     - web-dev
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.blitz-task-mailer.entrypoints=web"
  #     - "traefik.http.routers.blitz-task-mailer.rule=Host(`mail.blitz-task.docker.localhost`)"
  #     - "traefik.http.services.blitz-task-mailer.loadbalancer.server.port=8025"
###< symfony/mailer ###
